"""create Bet table

Revision ID: 239432a51915
Revises: 8eab31aa4303
Create Date: 2026-03-21 23:38:05.395740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '239432a51915'
down_revision: Union[str, Sequence[str], None] = '8eab31aa4303'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Bet',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('game_id', sa.BigInteger(), nullable=False),
    sa.Column('hash', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('target', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('cashout_multiplier', sa.Float(), nullable=False),
    sa.Column('winnings', sa.Float(), nullable=False),
    sa.Column('auto_cashout', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['Game.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Bet_game_id'), 'Bet', ['game_id'], unique=False)
    op.create_index(op.f('ix_Bet_hash'), 'Bet', ['hash'], unique=True)
    op.create_index(op.f('ix_Bet_id'), 'Bet', ['id'], unique=False)
    op.create_index(op.f('ix_Bet_user_id'), 'Bet', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Bet_user_id'), table_name='Bet')
    op.drop_index(op.f('ix_Bet_id'), table_name='Bet')
    op.drop_index(op.f('ix_Bet_hash'), table_name='Bet')
    op.drop_index(op.f('ix_Bet_game_id'), table_name='Bet')
    op.drop_table('Bet')
    # ### end Alembic commands ###
