"""add hash column to User table

Revision ID: 5eccb15d0153
Revises: 239432a51915
Create Date: 2026-03-22 00:28:47.044830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5eccb15d0153'
down_revision: Union[str, Sequence[str], None] = '239432a51915'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('hash', sa.String(), nullable=True))
    op.create_index(op.f('ix_User_hash'), 'User', ['hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_User_hash'), table_name='User')
    op.drop_column('User', 'hash')
    # ### end Alembic commands ###
