"""create Game table

Revision ID: 70dc599f88ba
Revises: 8b20e8dbe86e
Create Date: 2026-03-14 15:38:34.699714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70dc599f88ba'
down_revision: Union[str, Sequence[str], None] = '8b20e8dbe86e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Game',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('crash_point', sa.Float(), nullable=False),
    sa.Column('hash', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Game_created_at'), 'Game', ['created_at'], unique=False)
    op.create_index(op.f('ix_Game_hash'), 'Game', ['hash'], unique=True)
    op.create_index(op.f('ix_Game_id'), 'Game', ['id'], unique=False)
    op.create_index(op.f('ix_Game_status'), 'Game', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Game_status'), table_name='Game')
    op.drop_index(op.f('ix_Game_id'), table_name='Game')
    op.drop_index(op.f('ix_Game_hash'), table_name='Game')
    op.drop_index(op.f('ix_Game_created_at'), table_name='Game')
    op.drop_table('Game')
    # ### end Alembic commands ###
