"""create table Betside and add corresponding relationship under User table

Revision ID: 8eab31aa4303
Revises: 9ac8c4224247
Create Date: 2026-03-17 00:37:17.207611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8eab31aa4303'
down_revision: Union[str, Sequence[str], None] = '9ac8c4224247'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Betside',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('side_name', sa.String(), nullable=True),
    sa.Column('auto', sa.Boolean(), nullable=False),
    sa.Column('betted', sa.Boolean(), nullable=False),
    sa.Column('cashed_out', sa.Boolean(), nullable=False),
    sa.Column('cashout_amount', sa.Float(), nullable=False),
    sa.Column('bet_amount', sa.Float(), nullable=False),
    sa.Column('target', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Betside_id'), 'Betside', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Betside_id'), table_name='Betside')
    op.drop_table('Betside')
    # ### end Alembic commands ###
