"""add sid column to User table

Revision ID: 9ac8c4224247
Revises: 9bfaf7413dfc
Create Date: 2026-03-16 23:54:24.801203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ac8c4224247'
down_revision: Union[str, Sequence[str], None] = '9bfaf7413dfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('sid', sa.String(), nullable=True))
    op.create_index(op.f('ix_User_sid'), 'User', ['sid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_User_sid'), table_name='User')
    op.drop_column('User', 'sid')
    # ### end Alembic commands ###
