"""add pending_balance and unwagered_balance columns to User table

Revision ID: 9bfaf7413dfc
Revises: f897dba2ce5c
Create Date: 2026-03-16 04:15:41.884306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bfaf7413dfc'
down_revision: Union[str, Sequence[str], None] = 'f897dba2ce5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('pending_balance', sa.Float(), server_default='0.0', nullable=False))
    op.add_column('User', sa.Column('unwagered_balance', sa.Float(), server_default='0.0', nullable=False))
    op.create_index(op.f('ix_User_pending_balance'), 'User', ['pending_balance'], unique=False)
    op.create_index(op.f('ix_User_unwagered_balance'), 'User', ['unwagered_balance'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_User_unwagered_balance'), table_name='User')
    op.drop_index(op.f('ix_User_pending_balance'), table_name='User')
    op.drop_column('User', 'unwagered_balance')
    op.drop_column('User', 'pending_balance')
    # ### end Alembic commands ###
