"""add is_bot column to User table

Revision ID: f303f3ed6bca
Revises: 5eccb15d0153
Create Date: 2026-03-24 16:20:14.316422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f303f3ed6bca'
down_revision: Union[str, Sequence[str], None] = '5eccb15d0153'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('is_bot', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_User_is_bot'), 'User', ['is_bot'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_User_is_bot'), table_name='User')
    op.drop_column('User', 'is_bot')
    # ### end Alembic commands ###
