"""create Referral table and corresponding relationships

Revision ID: f897dba2ce5c
Revises: 70dc599f88ba
Create Date: 2026-03-14 21:42:28.302674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f897dba2ce5c'
down_revision: Union[str, Sequence[str], None] = '70dc599f88ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Referral',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('referred_id', sa.BigInteger(), nullable=False),
    sa.Column('referrer_id', sa.BigInteger(), nullable=False),
    sa.Column('referred_name', sa.String(), nullable=False),
    sa.Column('referrer_name', sa.String(), nullable=True),
    sa.Column('bonus_amount', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['referred_id'], ['User.id'], ),
    sa.ForeignKeyConstraint(['referrer_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Referral_id'), 'Referral', ['id'], unique=False)
    op.create_index(op.f('ix_Referral_referred_id'), 'Referral', ['referred_id'], unique=False)
    op.create_index(op.f('ix_Referral_referrer_id'), 'Referral', ['referrer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Referral_referrer_id'), table_name='Referral')
    op.drop_index(op.f('ix_Referral_referred_id'), table_name='Referral')
    op.drop_index(op.f('ix_Referral_id'), table_name='Referral')
    op.drop_table('Referral')
    # ### end Alembic commands ###
